spring:
  kafka:
    consumer:
      group-id: test-notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "org.example.dto"

  mail:
    host: localhost
    port: 3025
    username:
    password:
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false